title: Hongyun Du
description: Last Update at Jan. 2020
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
github:
zip_url: https://github.com/Yukikaze-Ai/Yukikaze-Ai.github.io/blob/master/docs/Resume%202020-15.pdf
